### ISSUE TITLE
Testing Images For Folder Giving Error

### ISSUE THREAD

**Issue by FlowDownTheRiver** [chaofengc/PSFRGAN#1]
Simple test image works with this command : python test_enhance_single_unalign.py --test_img_path ./test_dir/test_hzgg.jpg --results_dir test_hzgg_results --gpus 1

For folders : python align_and_crop_dir.py --src_dir test_dir --results_dir test_dir_align_results ////// works as well

but when I run this : python test_enhance_dir_align.py --dataroot test_dir_align_results --results_dir test_dir_enhance_results
I get an error : 

(psfrgan) C:\PSFRGAN>python test_enhance_dir_align.py --dataroot test_dir_align_results --results_dir test_dir_enhance_results
dataset [SingleDataset] was created
model [EnhanceModel] was created
Loading pretrained LQ face parsing network from ./pretrain_models/parse_multi_iter_90000.pth
Loading pretrained PSFRGAN from ./pretrain_models/psfrgan_latest_net_G.pth
creating result directory test_dir_enhance_results
  0%|                                                                                            | 0/8 [00:00<?, ?it/s]
  0%|                                                                                            | 0/4 [00:00<?, ?it/s]
  0%|                                                                                            | 0/8 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "test_enhance_dir_align.py", line 47, in <module>
    save_img.save((save_path))
  File "C:\Users\User\anaconda3\envs\psfrgan\lib\site-packages\PIL\Image.py", line 2155, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'test_dir_enhance_results\\lq\\test_dir_align_results\\Solvay_conference_1927_0.jpg'

I tried to change to a different version of pillow but non of them worked.
Also if you can fix this one,can we have a final result for the folder images as well? Because it says : Note: This is used to test a large amounts of data, and we do not paste the faces back.

I am on Windows 10 64 bit. 

Another question any way to use dfdnet models with your project?

**Comment by chaofengc** [comment]
This is because different OS use different path separators. I have update the codes to avoid explicit usage of separator in linux style. Please pull the latest version and try again.

For the folder images, you may try to write a bash file and use `test_enhance_single_unalign.py` file to process each image separately. Alternatively, you may also modify this file to handle folder images. We have no plan to provide final result for folder images, because current paste back operation is slow.

It  might be interesting to combine DFDNet models with our method, but we have no such plan at this time.

**Comment by FlowDownTheRiver** [comment]
Thank you very much.It exported the images with the new update.

Unfortunately I am very unfamiliar with python editing or with creating a bash file.

I have tested your test images,they are fast at pasting back the faces.Have also tested custom images with higher resolutions and they pasted back fast as well.I was able to run dlib on gpu and using 1080 ti,so everything works smooth.
Only thing that is holding me back is I don't know how to edit the your "single image python file" to read folder instead of 1 image,I have checked what is inside already and it exports as hqfinal.jpg.

I understand that I want it to read *.jpg and export as the same file name as the source image(so it doesn't get overwritten by the next file) and process the next image in the folder,but it is more complicated when you don't know how to do.

Please can you provide a python file which can do the operation? This is just a request. Pasting back works fast enough.

**Comment by chaofengc** [comment]
Well, I have added the script.

**Comment by FlowDownTheRiver** [comment]
Thank you very much for the script,it works as intended but there is another problem that seems to occur.
My first test image has 3 face and it outputs fine.When the model passes to the second image with multiple faces this time it gives cuda out of memory error for pytorch. If the second,third and so on images has single face it works.It seems like multiple faces in different images stays on the memory cache for pytorch and giving error. I checked the error from the internet and many has suggested droping the batch size,while others offered this : torch.cuda.empty_cache() ,but I don't know where to put it in python file,or how I can reduce the batch size. 

I also tried to lower the image resolution to see it is making the problem but it is not related with image resolution because when I remove the first image or the second image with multiple faces in the test folder the process goes without problem,until the next image with multi faces.

Full error report : (note that lambda error was not there,but it happened after I reduced the image size,so it is not a big deal,I think it is beause the image size is smaller than expected)

python test_enhance_dir_unalign.py --src_dir test_dir --results_dir test_unalign_results
model [EnhanceModel] was created
Loading pretrained LQ face parsing network from ./pretrain_models/parse_multi_iter_90000.pth
Loading pretrained PSFRGAN from ./pretrain_models/psfrgan_latest_net_G.pth
======> Loading image test_dir\0001.jpg
======> Saving aligned LQ faces to test_unalign_results\0001\LQ_faces
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.20it/s]
======> Save parsing map and the enhanced faces.
======> Paste the enhanced faces back to the original image.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:04<00:00,  1.34s/it]
======> Save final result to test_unalign_results\0001\hq_final.jpg
======> Loading image test_dir\0003.jpg
======> Saving aligned LQ faces to test_unalign_results\0003\LQ_faces
 33%|███████████████████████████████████████████████████████████████████                                                                                                                                      | 1/3 [00:00<00:01,  1.28it/s]
Traceback (most recent call last):
  File "test_enhance_dir_unalign.py", line 41, in <module>
    hq_faces, lq_parse_maps = enhance_faces(aligned_faces, enhance_model)
  File "C:\PSFRGAN\test_enhance_single_unalign.py", line 63, in enhance_faces
    parse_map, _ = model.netP(lq_tensor)
  File "C:\Users\User\anaconda3\envs\psfrgan\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\User\anaconda3\envs\psfrgan\lib\site-packages\torch\nn\parallel\data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\User\anaconda3\envs\psfrgan\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\PSFRGAN\models\networks.py", line 191, in forward
    x = self.decoder(x)
  File "C:\Users\User\anaconda3\envs\psfrgan\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\User\anaconda3\envs\psfrgan\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Users\User\anaconda3\envs\psfrgan\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\PSFRGAN\models\blocks.py", line 126, in forward
    res = self.conv2(res)
  File "C:\Users\User\anaconda3\envs\psfrgan\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\PSFRGAN\models\blocks.py", line 100, in forward
    out = self.relu(out)
  File "C:\Users\User\anaconda3\envs\psfrgan\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\PSFRGAN\models\blocks.py", line 70, in forward
    return self.func(x)
  File "C:\PSFRGAN\models\blocks.py", line 65, in <lambda>
    self.func = lambda x: x*1.0
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 11.00 GiB total capacity; 6.63 GiB already allocated; 4.42 MiB free; 6.94 GiB reserved in total by PyTorch)

Is it possible to clear the vram cache after each image processed or where can I lower the batch size?

**Comment by chaofengc** [comment]
Sorry, I forgot to disable gradient calculation during network inference. Should work fine now.

**Comment by FlowDownTheRiver** [comment]
I know you have closed the issue,but I just wanted to say big THANKS for everything for final.
Everything works perfect now and it is pasting the final faces fast.Great project,great results!!!
