### ISSUE TITLE
thanks for excellent work , i want to train your model with my own data, but i have some toruble with discriminitor D

### ISSUE THREAD

**Issue by erjihaoshi** [chaofengc/PSFRGAN#15]
networks.py
class NLayerDiscriminator(nn.Module):
nargs = {'norm_type': norm_type, 'relu_type': relu_type, 'ref_ch': ref_ch}
self.model.append(ConvLayer(cin, cout, scale='down', **nargs))
but the ConvLayer doesnot have  any parameters is related to 'ref_ch': ref_ch,
so could you tell what is worng?

**Comment by chaofengc** [comment]
Sorry, that's my mistake. You may simply remove the `ref_ch`. This is used to debug the performance of using parsing map or not in the discriminator. You should concatenate the parsing map and image as input of discriminator.

**Comment by erjihaoshi** [comment]
thanks ,by the way t.i think here is a mistake in networks.py

class NLayerDiscriminator(nn.Module):
 # self.input_ch = input_ch#原来
        self.input_ch = input_ch+ref_ch #修改
self.model.append(ConvLayer(self.input_ch, base_ch, norm_type='none', relu_type=relu_type))
I can train now,thanks for your work.
