### ISSUE TITLE
there is a error when translate the psfrgan_latest_net_G.pth to onnx.

### ISSUE THREAD

**Issue by zhangyunming** [chaofengc/PSFRGAN#17]
hi, thanks for the great work.

when i translate the psfrgan_latest_net_G.pth to onnx, there is a error ocuured, the parsing is ok.
![捕获](https://user-images.githubusercontent.com/12590457/104891140-7c064f00-59ab-11eb-8cc6-d252bd46fcd9.JPG)

can you give some advices. thanks

**Comment by chaofengc** [comment]
The restore model needs pair inputs: `(LR_image, parsing_map)`. You may try to combine them to one input and split them inside the forward function.

**Comment by zhangyunming** [comment]
hi， thank you so much . i have change the two input into one,  the reslut demo is same as two inputs

when i  translate to onnx , it said:
![捕获22](https://user-images.githubusercontent.com/12590457/104913272-4facfb80-59c8-11eb-954a-e35e7f00825a.JPG)

the 'mv' is not suport by onnx  9 10 11 12.

**Comment by chaofengc** [comment]
I am not familiar with ONNX and did not consider the code compatibility with onnx. You may have to debug the error and rewrite some operators by yourself.

**Comment by zhangyunming** [comment]
thanks , but i can not find the operator "mv", did you use the torch.mv in the code?

**Comment by chaofengc** [comment]
Most possible reason is that ONNX does not support `spectral_norm`. You may try to find if there are any solution to that.
