### ISSUE TITLE
what is the face parsing label?

### ISSUE THREAD

**Issue by zhangyunming** [chaofengc/PSFRGAN#18]
hi,  the parsing label in your code is?

it seems different from the celebaHQ mask label.

thanks

**Comment by zhangyunming** [comment]
![222](https://user-images.githubusercontent.com/12590457/106866661-b2f89680-6707-11eb-9ced-f4e5057f5d0e.jpg)
![daaadaaa](https://user-images.githubusercontent.com/12590457/106866758-cefc3800-6707-11eb-81dc-6c1cbb5178be.jpg)

**Comment by chaofengc** [comment]
The label is exactly the same with CelebAMask-HQ, please refer to the original codes: https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing/Data_preprocessing

**Comment by zhangyunming** [comment]
thank you  so much . 

if the parsing mask is the nearly same with yours ,does the restore reslut is nearly same ? my restore result is bad when the mask is pretty good as yours. why?

**Comment by chaofengc** [comment]
Please ensure the following if you use your own method to generate parsing map

- The input is onehot 
- The same label corresponds to the same parts. For example, 0-th channel should be background.
