### ISSUE TITLE
about color noise 

### ISSUE THREAD

**Issue by xiaohaipeng** [chaofengc/PSFRGAN#2]
with Semantic-Aware Style Loss, color noise problem in generated images can be solved ?

**Comment by chaofengc** [comment]
I am not sure what you mean by "color noise". The effectiveness of  L_ss is shown in Fig. 7 of the paper. It can help to alleviate some artifacts in the face region.

**Comment by xiaohaipeng** [comment]
Train SPADE for the same mission,color noise point or region more often appeared on eyes ,hair,just like in Fig.7 .I find spade without instance normolization can eliminate color noise point ,i want to make sure whether Semantic-Aware Style Loss can eliminate  the artifacts

**Comment by chaofengc** [comment]
The answer is yes in our experiments. But we are not sure whether it can be generalized to other tasks.
