### ISSUE TITLE
Any news about the training code?

### ISSUE THREAD

**Issue by sailor002** [chaofengc/PSFRGAN#22]
Hi, thanks for the great work. I know you already answered this but I would like to ask again because it has been a few months. Any plans to release the training codes? It would be awesome to try your model on different datasets. Thanks...

**Comment by chaofengc** [comment]
Thank you for your interest. Our paper has been accepted recently. We are rewriting the codes and retraining our models. The training codes will be released as soon as possible.

You may refer to another project for now: https://github.com/chaofengc/Face-SPARNet. The training parts are basically the same.
