### ISSUE TITLE
hi,when will release the train code?

### ISSUE THREAD

**Issue by zhangyunming** [chaofengc/PSFRGAN#23]
hi, it is a nice work in cvpr 2021, i have test it.

so will the whole training code relase? ，when about？

wait in hope.

**Comment by chaofengc** [comment]
We will release all the codes very soon. Please stay tuned.

Currently, you may refer to our another work: https://github.com/chaofengc/Face-SPARNet.git 
The training codes are basically the same. We have finished the codes of PSFRGAN but the retraining takes time.
