### ISSUE TITLE
CUDA out of memory.

### ISSUE THREAD

**Issue by monsterlyg** [chaofengc/PSFRGAN#25]
are you sure that the model can train on a single GPU with 8G memory.? As it needs to load four(G, D, P, VGG) networks during training. I cannot run train with a 12-G gpu.

**Comment by chaofengc** [comment]
Please check your batch size. I trained the model with batch_size=2 on two 1080Ti GPUs.

BTW, I do not have GPU device larger than 12-G gpu to train the model.
