### ISSUE TITLE
Loss_ss is 0.000

### ISSUE THREAD

**Issue by Wangyulin-user** [chaofengc/PSFRGAN#26]
Hello chaofeng, thank you for your wonderful work. I would like to ask why the Loss_ss is 0 when I trained with my own dataset? The masks I used are not generated by the net_P, and there are only a part of the images have the label masks, for example, my dataset is about brain, and only the tumor part of the brain has label. So could you please explain what's the Loss_ss equals to 0 means? And also the Loss_pcp is 0.

**Comment by Wangyulin-user** [comment]
And there is another question, I have only one kind of mask, and my training images are 3 channels, but I can only set --Dinput_nc=4, isn't it supposed to be 5 in my case? But if I set it 5, there is an error:"RuntimeError: Given groups = 1,weight of size[64, 5, 3, 3],expected input [4, 4, 514, 514] to have 5 channels, but got 4 channels instead". I found out it maybe because the ref channel is 1, should I change it somewhere?
Best regards,
yulin WANG

**Comment by chaofengc** [comment]
Thank you for interest. 

- For your first question, please make sure you correctly modify `RegionStyleLoss` for your data. There is a `region_num` parameter for this loss. At least two kinds of labels are required. `Loss_pcp` is not used in the paper, so we set its weight `--lambda_pcp` to zero by default.
- For the second question, please noted that the mask label should be converted to one hot format.

BTW: If you only want to calculate style loss for specific region, you need to make further modifications to the `RegionStyleLoss` class, for example, only use gram matrix for specific label in this function
https://github.com/chaofengc/PSFRGAN/blob/c882315c9f1fc91c43d13a709016dd411f73d713/models/loss.py#L192

**Comment by Wangyulin-user** [comment]
Thank you for your kindly explanation, now I set the region_num as 1 and I got Loss_SS even though it still so small like 0.006. So is there an ideal value for the Loss_ss? In view of it is MSE loss, is 0 the training goal?

**Comment by Wangyulin-user** [comment]
Thank you for your kindly explanation, now I set the region_num as 1 and I got Loss_SS even though it still so small like 0.006. So is there an ideal value for the Loss_ss? In view of it is MSE loss, is 0 the training goal?

**Comment by chaofengc** [comment]
The value of Loss_SS depends on your data. Similar to other networks, it is usually impossible to reach 0 if you use mini batch stochastic gradient descent.

**Comment by zhangyunming** [comment]
if use Loss_pcp , the result will be better? and lambda_pcp should be?

**Comment by chaofengc** [comment]
I tried with perceptual loss, but did not find improvement over visual quality. Perhaps will improve quantitative results. I did not test that.
