### ISSUE TITLE
a question about the result of Figure 6(b)

### ISSUE THREAD

**Issue by happyday521** [chaofengc/PSFRGAN#27]
Great work！ I have a question about the result of Figure 6(b).
Figure 6(b) shows the progressive restoration process when adding multi-scale inputs progressively. However, since the intermediate feature Fi doesn't goes through the ToRGB convolution layer, it is not in RGB format. How do you get the intermediate image result in the Figure，as follows:
![image](https://user-images.githubusercontent.com/35884085/114142065-03c57f00-9945-11eb-9caa-931f77766e70.png)

Thanks!

**Comment by chaofengc** [comment]
The visualisation result is obtained through a styleganv2 like framework which has a `torgb` block at each scale.
To reduce computation complexity, we remove them in the released version because it does not affect the performance.

**Comment by happyday521** [comment]
Got it. Thanks.
