### ISSUE TITLE
Fine-tuning on custom dataset

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [chaofengc/PSFRGAN#29]
Hi, I would like to use your work in a project of mine. I would like to fine-tune your pre-trained model on a custom dataset. To do so, I need the pre-trained discriminator. Could you share the "latest_net_D.pth" file? You can send it to lory.agnolucci@gmail.com.

Thanks in advance.

**Comment by chaofengc** [comment]
Sorry that I did not save the discriminator weight. Neither do I have access to the server now. You may try to train the network using the provided script. It takes about 3 - 5 days.

**Comment by maleficxp** [comment]
Hello! I've tried to launch train with parameters you provided and it shows approximate training time about 18 days. How can I do it in 3-5 days?

**Comment by chaofengc** [comment]
Duplicate of #33
