### ISSUE TITLE
does the result is normal?

### ISSUE THREAD

**Issue by zhangyunming** [chaofengc/PSFRGAN#31]
when i train my own data at 5000 iter.
the test reslut is:
![企业微信截图_16215100048305](https://user-images.githubusercontent.com/12590457/118971121-9c6a0880-b9a1-11eb-8539-255564c7a0be.png)
![企业微信截图_16215100449818](https://user-images.githubusercontent.com/12590457/118971128-9d9b3580-b9a1-11eb-8442-e0e52054a721.png)

**Comment by zhangyunming** [comment]
i know,
the test code of mine is before you relase the train code ,  i use the newest test code , the reslut is normal. maybe you updata the network or something when you release the train code .

**Comment by chaofengc** [comment]
Yes, the codes and models are all updated. Please use the latest version.
