### ISSUE TITLE
epoch num

### ISSUE THREAD

**Issue by zhangyunming** [chaofengc/PSFRGAN#33]
hi，in your train code the dauflt total epoch num is 50, but it cost even 20 days on my two 2080ti, and the model you given is 15 epoches ,does 15 is enough? 50 will have a better reslut than 15?

**Comment by chaofengc** [comment]
Yes, 15 epochs is enough. Training for more epochs does not bring much visual improvement. 
However, since I did not conduct full test for models with longer training. I am not sure whether it improves the generalization ability.
