### ISSUE TITLE
try to train 1024 resolution  memory out

### ISSUE THREAD

**Issue by goodclass** [chaofengc/PSFRGAN#34]
Hi, this is a great code

I try to train 1024 sizes， `Gout_size=1024` and `batch_size=1`
use RTX 3090 24G，Train one memory out of
Can some configurations be modified to adapt to a sample training

**Comment by chaofengc** [comment]
This is likely because of the style loss and 19 semantic maps. You may try to reduce the region number of parsing maps.
It is not that necessary to use all 19 regions.
