### ISSUE TITLE
about alignment operation

### ISSUE THREAD

**Issue by liuliuliu11** [chaofengc/PSFRGAN#36]
Hello, when training the parse network structure, does the FFHQ dataset used need not be aligned? The FFHQ-mask-512 data provided by Baidu Netdisk seems to be an unaligned 

According to  https://github.com/chaofengc/PSFRGAN/blob/82a8755116d61e83a302b7e48fb61c53c36e34c9/data/ffhq_dataset.py#L17，there is no alignment in the code

**Comment by chaofengc** [comment]
The mask images need to be aligned with the input RGB image, and therefore they are also aligned. Provided parsing masks are generated with a pretrained face parsing network (FPN) from the pre-aligned RGB images.
