### ISSUE TITLE
about generate_mask.py 

### ISSUE THREAD

**Issue by liuliuliu11** [chaofengc/PSFRGAN#37]
Thanks your great work~  When I use the trained model you provided and execute the ‘python generate_mask.py’ command，the output is as follows：
![1](https://user-images.githubusercontent.com/41572695/122022458-2ff3f500-cdf9-11eb-80c1-7065ec427a77.png)
![2](https://user-images.githubusercontent.com/41572695/122022471-32eee580-cdf9-11eb-94b0-a2a0fa7e36c6.png)
but there is a problem with the color of mask:
![00048](https://user-images.githubusercontent.com/41572695/122022495-397d5d00-cdf9-11eb-8043-9949244cfe84.png)

**Comment by chaofengc** [comment]
Thank you for interest. I git pull the code and tested it again. The model works well. I cannot reproduce your problem. Please give more details if possible.
