### ISSUE TITLE
Cuda ran out of memory.

### ISSUE THREAD

**Issue by 3BBUAE** [chaofengc/PSFRGAN#39]
Hello, I am trying to train the enhancer model from scratch, but for some reason the GPU runs out of memory.
It is a 12GB Nvidia gtx 1080, I have set it to batch size of 1, I have tried using different image sizes (1024,720, and 512).

`python train.py --gpus 1 --model enhance --name PSFRGAN_V001 --g_lr 0.0001 --d_lr 0.0004 --beta1 0.5 --gan_mode 'hinge' --lambda_pix 10 --lambda_fm 10 --lambda_ss 1000 --Dinput_nc 22 --D_num 3 --n_layers_D 4 --batch_size 2 --dataset ffhq --dataroot ./datasets/FFHQ --visual_freq 100 --print_freq 10 --n_epochs 25`

![Screenshot from 2021-07-07 11-15-48](https://user-images.githubusercontent.com/15378788/124716276-f48aa900-df14-11eb-8962-52d502d69ba0.png)

Thanks for sharing your work.

**Comment by chaofengc** [comment]
It seems that `--batch_size 2` is in your command. The model needs at least 8GB memory to train with batch_size=1, 512x512 inputs.

**Comment by 3BBUAE** [comment]
Thanks for the quick response, I can't believe I missed that.
it worked and is currently training thank you.
