### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by shenhaiyoualn** [chaofengc/PSFRGAN#42]
我有一个疑问，你们这个模型是一个GAN模型，为什么没有判别器呢？

**Comment by chaofengc** [comment]
如果是网络结构问题，请仔细阅读论文以及代码。如果你问的是预训练模型，由于测试阶段不需要用到，因此没有release预训练的discriminator。需要的话，可以自行按照README的说明训练。

**Comment by shenhaiyoualn** [comment]
在论文的4.1中的LR是不是应该写成LQ? LR应该是超分领域的术语 ，感谢您的回答！
