### ISSUE TITLE
A question about training the FPN

### ISSUE THREAD

**Issue by JimjimChen** [chaofengc/PSFRGAN#45]
![微信图片_20211126162849](https://user-images.githubusercontent.com/35997309/143550686-a66a2573-c8a0-4687-8c84-194717e3d73d.png)
![微信图片_20211126162941](https://user-images.githubusercontent.com/35997309/143550698-14dd4372-92ca-41f2-9c68-3c6910b4e221.png)

First of all, thank you very much for your work. I met the above problem when I trained FPN. Do you know how to solve it？ Looking forward to your reply.

**Comment by chaofengc** [comment]
It seems that your data is incorrect. Please follow readme and generate the correct data.

> Download CelebAHQ-Mask dataset. Generate `CelebAMask-HQ-mask` and `CelebAMask-HQ-mask-color` with the provided scripts in CelebAMask-HQ/face_parsing/Data_preprocessing/.

After that, put the folder `CelebAMask-HQ-mask` and `CelebAMask-HQ-mask-color`  under `../datasets/CelebAMask-HQ`

**Comment by JimjimChen** [comment]
> It seems that your data is incorrect. Please follow readme and generate the correct data.
> 
> > Download CelebAHQ-Mask dataset. Generate `CelebAMask-HQ-mask` and `CelebAMask-HQ-mask-color` with the provided scripts in CelebAMask-HQ/face_parsing/Data_preprocessing/.
> 
> After that, put the folder `CelebAMask-HQ-mask` and `CelebAMask-HQ-mask-color` under `../datasets/CelebAMask-HQ`

Many thanks！I have another question： when I finished generating 'CelebAMask-HQ-mask' , is the next step  to run 'g_color.py’ directly?  
When I run 'g_color.py' , I met a error : NameError : name 'im_base' is not defined. Do you know how to fix it？
![微信图片_20211128104100](https://user-images.githubusercontent.com/35997309/143726780-4c6b96d6-8e1e-45c6-8340-512f67f1980d.png)

**Comment by chaofengc** [comment]
Actually, training FPN does not need the colored mask. Please refer to the code:

https://github.com/chaofengc/PSFRGAN/blob/82a8755116d61e83a302b7e48fb61c53c36e34c9/data/celebahqmask_dataset.py#L28-L29

You may simply put the generated mask folder `CelebAMask-HQ-mask` and corresponding image folder `CelebA-HQ-img` under the `dataroot`.
