### ISSUE TITLE
what's F0 in the paper?

### ISSUE THREAD

**Issue by tachikoma777** [chaofengc/PSFRGAN#46]
There is F0 as network input, may i ask how it is used?

**Comment by tachikoma777** [comment]
The paper says "It starts with a learned constant of size C*16*16, denoted as F0, where C is the channel size. But what's the value should be? is it the same for every image?

**Comment by chaofengc** [comment]
It is a learnable parameter of size `C x 16 x 16`.

**Comment by tachikoma777** [comment]
Sorry if I bother you, but i still dont know how it is calculated, could you be more specific? Thanks a lot!
