### ISSUE TITLE
测试FPN时遇到了一个问题

### ISSUE THREAD

**Issue by JimjimChen** [chaofengc/PSFRGAN#47]
![微信图片_20211202155628](https://user-images.githubusercontent.com/35997309/144380921-09083e27-d338-45c4-bcbb-655a1f947cfa.png)
![QQ截图20211202155602](https://user-images.githubusercontent.com/35997309/144380929-58ed5307-dd01-41a6-91c9-225c811d1902.png)
作者您好！您知道这个问题如何解决吗，我的路径好像没有问题阿。期待您的回复。

**Comment by chaofengc** [comment]
Please specify the `--src_dir` option, where your test images are stored.
