### ISSUE TITLE
Thank you for your work. After I retrained netG, there are obvious boundaries on the edges of the face

### ISSUE THREAD

**Issue by leslie-ds** [chaofengc/PSFRGAN#49]
Thank you for your work. After I retrained netG, there are obvious boundaries on the edges of the face
![Screenshot from 2021-12-05 11-21-47](https://user-images.githubusercontent.com/72796432/144732226-79ee94e9-8e2e-49e9-9eec-dc2a9e3a228a.jpg)

**Comment by chaofengc** [comment]
Please note that our method only process the face region. The low quality faces are first cropped out, enhanced and then paste back to the original image. Therefore, background regions are not processed, resulting in the boundary edges. 

You may refer to the more recent work GFPGAN for better performance: https://github.com/TencentARC/GFPGAN
