### ISSUE TITLE
测试FPN时需要psfrgan_epoch15_net_G.pth吗

### ISSUE THREAD

**Issue by JimjimChen** [chaofengc/PSFRGAN#51]
作者您好，想请问您psfrgan_epoch15_net_G.pth在测试FPN是起什么作用呢，以及测试时我发现输入的FFHQ是清晰图片，网络是自己生成LR吗？

**Comment by chaofengc** [comment]
测试FPN不需要`psfrgan_epoch15_net_G.pth`. Parsing Net 和 SR Net是分开的两个网络.

第二个问题不太清晰。测试时是没有清晰图片的。训练时的LR图片是模拟生成的。
