### ISSUE TITLE
CelebAHQ-Test

### ISSUE THREAD

**Issue by dfgaeg** [chaofengc/PSFRGAN#57]
Dear author, may I ask whether the CelebAHQ-Test results such as (PSNR,SSIM) about HiFaceGAN and DFDNet mentioned in your paper were trained under the same training data set by yourself, or directly tested with the provided pre-trained model ? Thank you for your reply.

**Comment by chaofengc** [comment]
Because both of them (including our model) applied similar online-degradation pipeline, we compared with the provided pre-trained model. You may have to retrain the model if you use different degradation pipeline.
