### ISSUE TITLE
2 Important Requests If Possible

### ISSUE THREAD

**Issue by FlowDownTheRiver** [chaofengc/PSFRGAN#8]
When running the test_enhance_dir_unalign.py I had around 800 images.It gave error on some images due to some pictures are not oriented right,some were very low resolution and for whatever reasons.Anyway it gives error and stops the process,as you can see image 0623 is done,0624 gave error.

My first request is can it just,bypass the error and go to the next file ? 623 fine,624 error(and skip without stopping the process), and do 625 and so on?

My second request is if we have 100 images for example,can the folder processing check "test_unalign_results" folder and auto skip if 45 of the images already exported as into folders(HQ,LQ_faces,ParseMaps) and go from the 46th image if we start the processing back again from start(or if an error happens)?

Edit : Maybe another solution of doing it,cut&paste the files that are giving error like no faces detected,to a directory named "test_dir_troubleshoot" automatically,so they are bypassed and then we may know which are the problematic images,and it keeps processing the files which are fine.

Here, is when it stoped the process...

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  5.89it/s]
======> Save parsing map and the enhanced faces.
======> Loading image test_dir\0623.jpg
======> Saving aligned LQ faces to test_unalign_results\0623\LQ_faces
100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  5.82it/s]
======> Save parsing map and the enhanced faces.
======> Loading image test_dir\0624.jpg
Traceback (most recent call last):
  File "test_enhance_dir_unalign_crop.py", line 34, in <module>
    aligned_faces, tform_params = detect_and_align_faces(img, face_detector, lmk_predictor, template_path)
  File "C:\PSFRGAN\test_enhance_single_unalign.py", line 24, in detect_and_align_faces
    assert len(face_dets) > 0, 'No faces detected'
AssertionError: No faces detected
-------------------------------------------------------------------------------------------------------------

If you can do it please,it will be excellent!

**Comment by chaofengc** [comment]
I am sorry that this project is just a demo for our project. We have no plan and time to handle errors when processing a large amount of unaligned images.

**Comment by FlowDownTheRiver** [comment]
Thank you very much anyway.If or when you have time to make some edits here and there it is more than welcome.I love this project.
